---
     - name: Update repositories cache
       apt: update_cache=yes
 
     - name: install apache2 web server
       apt: name=apache2 state=latest
 
     - name: Start apache2 server
       service: name=apache2 state=started

