---
    - name: Add PHP 7 PPA repository
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: install mysql and php with dependencies
      apt: pkg={{ item }} state=latest
      with_items:
      - git
      - mysql-server
      - php7.2
      - php7.2-mysql
      - php7.2-gd
      - php7.2-mbstring
      - curl
      - php7.2-curl
      - python-mysqldb
      - expect
      - php7.0-mcrypt
      - php7.2-bcmath
      - php7.2-curl
      - php7.2-gmp
      - php7.2-ldap
      - php7.2-zip
      - php7.2-xml
      - libapache2-mod-php7.2
      - php7.2-common
      - php7.2-intl
      - php7.2-pear
      - php7.2-imagick
      - php7.2-imap 
      - php7.2-memcache
      - php7.2-pspell
      - php7.2-recode
      - php7.2-sqlite3
      - php7.2-tidy
      - php7.2-xmlrpc
      - php7.2-xsl
      - php7.2-gettext  

    - name: start mysql db 
      service: name=mysql  enabled=yes state=started          
