---
    - name: Add PHP 7 PPA repository
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: install mysql and php with dependencies
      apt: pkg={{ item }} state=latest
      with_items:
      - git
      - mysql-server
      - php7.2
      - php7.2-mysql
      - php7.2-gd
      - php7.2-mbstring
      - php7.2-curl
      - python-mysqldb
      - php7.2-bcmath
      - php7.2-curl
      - php7.2-gmp
      - php7.2-zip
      - php7.2-xml
      - libapache2-mod-php7.2
      - php7.2-common
      - php7.2-intl
      - php7.2-sqlite3
      - php7.2-xmlrpc 
    
   
    - name: start mysql db 
      service: name=mysql  enabled=yes state=started          
