---
# tasks file for snipeit
 - name: to install apache
   include: apache.yml

 - name: secure install mysql
   include: secureinstall.yml

 - name: to install php 
   include: installpackages.yml

 - name: Add php test page
   include: phptest.yml

 - name: download and setup composer 
   include: composer.yml

 - name: clone snipe-it repo
   include: snipeit_clone.yml

 - name: setup database
   include: setup_db.yml

 - name: make changes to .env file
   include: env.yml

 - name: Adjust permissions
   include: permission.yml

 - name: Install composer
   include: install_composer.yml 

 - name: Generate app key
   include: appkey.yml

 - name: add virtual host file
   include: virtualhost.yml

 - name: Enable php extensions
   include: php_extn.yml  
